// Mocks generated by Mockito 5.4.1 from annotations
// in movie_app/test/features/movie_detail/data/datasources/movie_detail_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/src/core/api_client/api_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> getHeaders() => (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);
  @override
  dynamic get(
    String? path, {
    Map<dynamic, dynamic>? params,
  }) =>
      super.noSuchMethod(Invocation.method(
        #get,
        [path],
        {#params: params},
      ));
  @override
  String getFullPath(
    String? path,
    Map<dynamic, dynamic>? params,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullPath,
          [
            path,
            params,
          ],
        ),
        returnValue: '',
      ) as String);
}
